spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5433/taskdb
    username: taskuser
    password: taskpass
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

data:
  web:
    pageable:
      max-page-size: 20
